// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egysirnxcsklkzqcyogc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVneXNpcm54Y3NrbGt6cWN5b2djIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MTQxMDEsImV4cCI6MjA2ODI5MDEwMX0.3TbEywhazGXJyoo_2VrlesSssVUNFAhRMy02b9IOFE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});